# Generated by Django 4.2 on 2023-05-06 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentapps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='add_student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_code', models.CharField(max_length=255)),
                ('s_name', models.CharField(max_length=255)),
                ('s_add', models.CharField(max_length=255)),
                ('s_age', models.IntegerField()),
                ('s_gen', models.CharField(max_length=255)),
                ('s_mail', models.EmailField(max_length=254)),
            ],
        ),
    ]
